# Generated by Django 5.2 on 2026-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='noutbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
